### ISSUE TITLE
为什么我写了一个包含 lobash 的脚本 1.sh，只能用 "./1.sh" 方式运行，而不能用 "sh 1.sh"？

### ISSUE THREAD

**Issue by yiding-he** [adoyle-h/lobash#2]

**Comment by yiding-he** [comment]
![ubuntu_2019-07-02_10-58-25](https://user-images.githubusercontent.com/900606/60479437-655cb200-9cb8-11e9-8a92-cf37b8c71095.png)

**Comment by adoyle-h** [comment]
`which sh` 看下用的是是不是 `/bin/sh`，如果是的话，`sh 1.sh` 调用的是 sh 而非 bash。
具体不同请见 https://askubuntu.com/questions/141928/what-is-the-difference-between-bin-sh-and-bin-bash

如果问题已解决，请自行 close issue。

**Comment by jo-wu** [comment]
try “bash 1.sh”

**Comment by adoyle-h** [comment]
先关闭了，如有疑问请留言。
