### ISSUE TITLE
Dead link in README.md

### ISSUE THREAD

**Issue by AriESQ** [adoyle-h/lobash#6]
## Describe the bug

At location: https://github.com/adoyle-h/lobash/blob/develop/README.md?plain=1#L176

The link is dead. The updated link is: https://dougrichardson.us/notes/fail-fast-bash-scripting.html

## Additional context

I would have made a PR, but the contributions requirements are too much for a typo bugfix.  
Thank you for a great project.

**Comment by adoyle-h** [comment]
Thank you
